# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrossDK-demo SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrossDK-demo SwiftUI
  pod 'CrossDK', :git => 'git@github.com:Adikteev/crossdk-ios.git'

end
