#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
#ifndef CROSSDK_SWIFT_H
#define CROSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
@import StoreKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CrossDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSNumber;
@class NSString;

/// Configuration class for <code>CrossDK</code>.
SWIFT_CLASS("_TtC7CrossDK13CrossDKConfig")
@interface CrossDKConfig : NSObject
/// Shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CrossDKConfig * _Nonnull shared;)
+ (CrossDKConfig * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Returns whether <code>CrossDK</code> is properly configured.
@property (nonatomic, readonly) BOOL isConfigured;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Sets up configuration for <code>CrossDK</code>.
/// \param appId current application’s App Store ID
///
/// \param apiKey authorization API key
///
/// \param userId user’s ID
///
- (void)setupWithAppId:(NSString * _Nonnull)appId apiKey:(NSString * _Nonnull)apiKey userId:(NSString * _Nullable)userId;
@end


@protocol CrossDKOverlayDelegate;
@protocol CrossDKVideoOverlayDelegate;
@class UIWindow;
enum OverlayPosition : NSInteger;
enum VideoOverlayPosition : NSInteger;

/// Handles CrossDK’s overlays display.
SWIFT_CLASS("_TtC7CrossDK14CrossDKOverlay")
@interface CrossDKOverlay : NSObject
@property (nonatomic, weak) id <CrossDKOverlayDelegate> _Nullable delegateOverlay;
@property (nonatomic, weak) id <CrossDKVideoOverlayDelegate> _Nullable delegateVideoOverlay;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Displays an Overlay view.
/// \param window current window
///
/// \param position overlay position
///
- (void)displayOverlayWithWindow:(UIWindow * _Nonnull)window position:(enum OverlayPosition)position;
/// Dismisses an Overlay view.
/// \param window current window
///
- (void)dismissOverlayWithWindow:(UIWindow * _Nonnull)window;
/// Displays a Video Overlay view controller.
/// \param window current window
///
/// \param position overlay position
///
- (void)displayVideoOverlayWithWindow:(UIWindow * _Nonnull)window position:(enum VideoOverlayPosition)position;
/// Dismisses the Video Overlay view controller.
- (void)dismissVideoOverlay;
/// Adds a button to dismiss the Overlay view.
/// \param isHidden show / hide close button
///
- (void)closeButtonWithIsHidden:(BOOL)isHidden;
@end

/// Identifies the position of an overlay on the screen.
typedef SWIFT_ENUM(NSInteger, OverlayPosition, open) {
/// Specifies that the overlay is at the bottom of the screen.
  OverlayPositionBottom = 0,
/// Specifies that the overlay is at a raised position at the bottom of the screen.
  OverlayPositionBottomRaised = 1,
};

/// Identifies the position of a video overlay on the screen.
typedef SWIFT_ENUM(NSInteger, VideoOverlayPosition, open) {
/// Specifies that the overlay is at the bottom of the screen.
  VideoOverlayPositionBottom = 0,
/// Specifies that the overlay is at a raised position at the bottom of the screen.
  VideoOverlayPositionBottomRaised = 1,
};

typedef SWIFT_ENUM(NSInteger, OverlayError, open) {
/// Indicates that current OS version is not supported.
  OverlayErrorUnsupportedOSVersion = 0,
/// Indicates that a scene couldn’t be retrieved from given <code>UIWindow</code>.
  OverlayErrorUnavailableWindowScene = 1,
/// Indicates that no recommendation is available at the moment.
  OverlayErrorUnavailableRecommendation = 2,
/// Indicates that <code>CrossDK</code> is not properly configured.
  OverlayErrorNoConfiguration = 3,
};


@class SKOverlay;
@class SKOverlayTransitionContext;

SWIFT_AVAILABILITY(ios,introduced=14.0)
@interface CrossDKOverlay (SWIFT_EXTENSION(CrossDK)) <SKOverlayDelegate>
/// Indicates that the platform presents an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ willStartPresentation:(SKOverlayTransitionContext * _Nonnull)_;
/// Indicates that the platform is finished presenting an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ didFinishPresentation:(SKOverlayTransitionContext * _Nonnull)_;
/// Indicates that the platform dismisses an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ willStartDismissal:(SKOverlayTransitionContext * _Nonnull)_;
/// Indicates that the platform finished dismissing an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ didFinishDismissal:(SKOverlayTransitionContext * _Nonnull)_;
/// Indicates that the platform failed to load an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ didFailToLoadWithError:(NSError * _Nonnull)error;
@end


/// Delegate that gets notified on overlay video state changes.
SWIFT_PROTOCOL("_TtP7CrossDK27CrossDKVideoOverlayDelegate_")
@protocol CrossDKVideoOverlayDelegate
/// Indicates that the platform is finished presenting an overlay.
- (void)videoOverlayDidFinishPresentation;
/// Indicates that the platform finished dismissing an overlay.
- (void)videoOverlayDidFinishDismissal;
/// Indicates that the platform shows a recommended app in the App Store.
- (void)videoOverlayShowsRecommendedAppInAppStore;
/// Indicates that the platform starts playing the video.
- (void)videoOverlayStartsPlayingVideo;
/// Indicates that the platform played half of the video.
- (void)videoOverlayPlayedHalfVideo;
/// Indicates that the platform has finished playing the video.
- (void)videoOverlayDidFinishPlayingVideo;
/// Indicates that the platform failed to load an overlay.
- (void)videoOverlayDidFailToLoad;
/// Indicates that the overlay is not available.
/// \param error an error describing encountered issue
///
- (void)videoOverlayUnavailableWithError:(enum OverlayError)error;
@end


@interface CrossDKOverlay (SWIFT_EXTENSION(CrossDK)) <CrossDKVideoOverlayDelegate>
/// Indicates that the platform is finished presenting an overlay.
- (void)videoOverlayDidFinishPresentation;
/// Indicates that the platform finished dismissing an overlay.
- (void)videoOverlayDidFinishDismissal;
/// Indicates that the platform shows a recommended app in the App Store.
- (void)videoOverlayShowsRecommendedAppInAppStore;
/// Indicates that the platform starts playing the video.
- (void)videoOverlayStartsPlayingVideo;
/// Indicates that the platform played half of the video.
- (void)videoOverlayPlayedHalfVideo;
/// Indicates that the platform has finished playing the video.
- (void)videoOverlayDidFinishPlayingVideo;
/// Indicates that the platform failed to load an overlay.
- (void)videoOverlayDidFailToLoad;
/// Indicates that an overlay is unavailable.
- (void)videoOverlayUnavailableWithError:(enum OverlayError)error;
@end


/// Delegate that gets notified on overlay state changes.
SWIFT_PROTOCOL("_TtP7CrossDK22CrossDKOverlayDelegate_")
@protocol CrossDKOverlayDelegate
/// Indicates that the platform presents an overlay.
- (void)overlayWillStartPresentation;
/// Indicates that the platform is finished presenting an overlay.
- (void)overlayDidFinishPresentation;
/// Indicates that the platform dismisses an overlay.
- (void)overlayWillStartDismissal;
/// Indicates that the platform finished dismissing an overlay.
- (void)overlayDidFinishDismissal;
/// Indicates that the platform failed to load an overlay.
- (void)overlayDidFailToLoadWithError:(NSError * _Nonnull)error;
/// Indicates that the overlay is not available.
/// \param error an error describing encountered issue
///
- (void)overlayUnavailableWithError:(enum OverlayError)error;
@end




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
#ifndef CROSSDK_SWIFT_H
#define CROSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
@import StoreKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CrossDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSNumber;
@class NSString;

/// Configuration class for <code>CrossDK</code>.
SWIFT_CLASS("_TtC7CrossDK13CrossDKConfig")
@interface CrossDKConfig : NSObject
/// Shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CrossDKConfig * _Nonnull shared;)
+ (CrossDKConfig * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Returns whether <code>CrossDK</code> is properly configured.
@property (nonatomic, readonly) BOOL isConfigured;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Sets up configuration for <code>CrossDK</code>.
/// \param appId current application’s App Store ID
///
/// \param apiKey authorization API key
///
/// \param userId user’s ID
///
- (void)setupWithAppId:(NSString * _Nonnull)appId apiKey:(NSString * _Nonnull)apiKey userId:(NSString * _Nullable)userId;
@end


@protocol CrossDKOverlayDelegate;
@protocol CrossDKVideoOverlayDelegate;
@class UIWindow;
enum OverlayPosition : NSInteger;
enum VideoOverlayPosition : NSInteger;

/// Handles CrossDK’s overlays display.
SWIFT_CLASS("_TtC7CrossDK14CrossDKOverlay")
@interface CrossDKOverlay : NSObject
@property (nonatomic, weak) id <CrossDKOverlayDelegate> _Nullable delegateOverlay;
@property (nonatomic, weak) id <CrossDKVideoOverlayDelegate> _Nullable delegateVideoOverlay;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Displays an Overlay view.
/// \param window current window
///
/// \param position overlay position
///
- (void)displayOverlayWithWindow:(UIWindow * _Nonnull)window position:(enum OverlayPosition)position;
/// Dismisses an Overlay view.
/// \param window current window
///
- (void)dismissOverlayWithWindow:(UIWindow * _Nonnull)window;
/// Displays a Video Overlay view controller.
/// \param window current window
///
/// \param position overlay position
///
- (void)displayVideoOverlayWithWindow:(UIWindow * _Nonnull)window position:(enum VideoOverlayPosition)position;
/// Dismisses the Video Overlay view controller.
- (void)dismissVideoOverlay;
/// Adds a button to dismiss the Overlay view.
/// \param isHidden show / hide close button
///
- (void)closeButtonWithIsHidden:(BOOL)isHidden;
@end

/// Identifies the position of an overlay on the screen.
typedef SWIFT_ENUM(NSInteger, OverlayPosition, open) {
/// Specifies that the overlay is at the bottom of the screen.
  OverlayPositionBottom = 0,
/// Specifies that the overlay is at a raised position at the bottom of the screen.
  OverlayPositionBottomRaised = 1,
};

/// Identifies the position of a video overlay on the screen.
typedef SWIFT_ENUM(NSInteger, VideoOverlayPosition, open) {
/// Specifies that the overlay is at the bottom of the screen.
  VideoOverlayPositionBottom = 0,
/// Specifies that the overlay is at a raised position at the bottom of the screen.
  VideoOverlayPositionBottomRaised = 1,
};

typedef SWIFT_ENUM(NSInteger, OverlayError, open) {
/// Indicates that current OS version is not supported.
  OverlayErrorUnsupportedOSVersion = 0,
/// Indicates that a scene couldn’t be retrieved from given <code>UIWindow</code>.
  OverlayErrorUnavailableWindowScene = 1,
/// Indicates that no recommendation is available at the moment.
  OverlayErrorUnavailableRecommendation = 2,
/// Indicates that <code>CrossDK</code> is not properly configured.
  OverlayErrorNoConfiguration = 3,
};


@class SKOverlay;
@class SKOverlayTransitionContext;

SWIFT_AVAILABILITY(ios,introduced=14.0)
@interface CrossDKOverlay (SWIFT_EXTENSION(CrossDK)) <SKOverlayDelegate>
/// Indicates that the platform presents an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ willStartPresentation:(SKOverlayTransitionContext * _Nonnull)_;
/// Indicates that the platform is finished presenting an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ didFinishPresentation:(SKOverlayTransitionContext * _Nonnull)_;
/// Indicates that the platform dismisses an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ willStartDismissal:(SKOverlayTransitionContext * _Nonnull)_;
/// Indicates that the platform finished dismissing an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ didFinishDismissal:(SKOverlayTransitionContext * _Nonnull)_;
/// Indicates that the platform failed to load an overlay.
- (void)storeOverlay:(SKOverlay * _Nonnull)_ didFailToLoadWithError:(NSError * _Nonnull)error;
@end


/// Delegate that gets notified on overlay video state changes.
SWIFT_PROTOCOL("_TtP7CrossDK27CrossDKVideoOverlayDelegate_")
@protocol CrossDKVideoOverlayDelegate
/// Indicates that the platform is finished presenting an overlay.
- (void)videoOverlayDidFinishPresentation;
/// Indicates that the platform finished dismissing an overlay.
- (void)videoOverlayDidFinishDismissal;
/// Indicates that the platform shows a recommended app in the App Store.
- (void)videoOverlayShowsRecommendedAppInAppStore;
/// Indicates that the platform starts playing the video.
- (void)videoOverlayStartsPlayingVideo;
/// Indicates that the platform played half of the video.
- (void)videoOverlayPlayedHalfVideo;
/// Indicates that the platform has finished playing the video.
- (void)videoOverlayDidFinishPlayingVideo;
/// Indicates that the platform failed to load an overlay.
- (void)videoOverlayDidFailToLoad;
/// Indicates that the overlay is not available.
/// \param error an error describing encountered issue
///
- (void)videoOverlayUnavailableWithError:(enum OverlayError)error;
@end


@interface CrossDKOverlay (SWIFT_EXTENSION(CrossDK)) <CrossDKVideoOverlayDelegate>
/// Indicates that the platform is finished presenting an overlay.
- (void)videoOverlayDidFinishPresentation;
/// Indicates that the platform finished dismissing an overlay.
- (void)videoOverlayDidFinishDismissal;
/// Indicates that the platform shows a recommended app in the App Store.
- (void)videoOverlayShowsRecommendedAppInAppStore;
/// Indicates that the platform starts playing the video.
- (void)videoOverlayStartsPlayingVideo;
/// Indicates that the platform played half of the video.
- (void)videoOverlayPlayedHalfVideo;
/// Indicates that the platform has finished playing the video.
- (void)videoOverlayDidFinishPlayingVideo;
/// Indicates that the platform failed to load an overlay.
- (void)videoOverlayDidFailToLoad;
/// Indicates that an overlay is unavailable.
- (void)videoOverlayUnavailableWithError:(enum OverlayError)error;
@end


/// Delegate that gets notified on overlay state changes.
SWIFT_PROTOCOL("_TtP7CrossDK22CrossDKOverlayDelegate_")
@protocol CrossDKOverlayDelegate
/// Indicates that the platform presents an overlay.
- (void)overlayWillStartPresentation;
/// Indicates that the platform is finished presenting an overlay.
- (void)overlayDidFinishPresentation;
/// Indicates that the platform dismisses an overlay.
- (void)overlayWillStartDismissal;
/// Indicates that the platform finished dismissing an overlay.
- (void)overlayDidFinishDismissal;
/// Indicates that the platform failed to load an overlay.
- (void)overlayDidFailToLoadWithError:(NSError * _Nonnull)error;
/// Indicates that the overlay is not available.
/// \param error an error describing encountered issue
///
- (void)overlayUnavailableWithError:(enum OverlayError)error;
@end




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
